version: '3.5'
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    env_file:
      - .env
    volumes:
       - postgres:/data/postgres
       - ./data/script.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
  api:
    container_name: uniftc_api_container
    image: tiberiusbr/apiplabos
    env_file:
      - .env
    volumes:
    # This creates a shortcut where docker will be able to access host files.
      - /home/nodge/Development/plabos_videos:/api/app/files
    ports:
      - "8000:8000"
    links:
      - postgres
volumes:
  postgres:

